version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      BOOTSTRAP_SERVERS: localhost:9092  # Kafka locally installed
      ELASTICSEARCH_HOST: localhost:9200  # Elasticsearch locally installed
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app  
    command: python app/main.py



  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app  
      - /usr/src/app/node_modules  
    command: npm start
