name: CI/CD for Reddit Sentiment Analysis

# Triggers the workflow on push or pull request to main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_backend:
    runs-on: ubuntu-latest

    services:
      # This sets up a Kafka service to run alongside the backend tests
      kafka:
        image: 'wurstmeister/kafka:latest'
        ports:
          - 9092:9092
        options: --name kafka --hostname kafka

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Backend Docker Image
        run: docker build -t reddit-metric-analysis-backend ./backend

      - name: Push Backend Docker Image
        run: |
          docker tag reddit-metric-analysis-backend <your-dockerhub-username>/reddit-metric-analysis-backend:latest
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push <your-dockerhub-username>/reddit-metric-analysis-backend:latest

  build_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Frontend Docker Image
        run: docker build -t reddit-metric-analysis-frontend ./frontend

      - name: Push Frontend Docker Image
        run: |
          docker tag reddit-metric-analysis-frontend <your-dockerhub-username>/reddit-metric-analysis-frontend:latest
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push <your-dockerhub-username>/reddit-metric-analysis-frontend:latest

  deploy:
    needs: [build_backend, build_frontend]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server (Docker Compose)
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
          docker pull <your-dockerhub-username>/reddit-metric-analysis-backend:latest
          docker pull <your-dockerhub-username>/reddit-metric-analysis-frontend:latest
          cd /path/to/docker-compose/
          docker-compose down
          docker-compose up -d
          EOF
